
--------------------------------------------------------------------------------
 INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES IN CONTACT PAIRS THAT
Abaqus/Explicit WILL ATTEMPT TO RESOLVE WITH STRAIN-FREE ADJUSTMENTS TO
POSITIONS OF DEFORMABLE SLAVE NODES
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
 INITIAL OVERCLOSURE ADJUSTMENTS BY NODE
--------------------------------------------------------------------------------

Adjustment for initial overclosure is 3.33067E-16 at node 81
     of instance BAN-1

--------------------------------------------------------------------------------
